pipeline:
  build:
    image: genee/gini-dev:alpine
    commands:
      - >
        for FILE in $(find {class,view} -name "*.php" -o -name "*.phtml"); do
          php --syntax-check "$FILE"
        done
      - bin/gini composer init -f
      - composer install --no-interaction --no-dev
      - bin/gini cache
      - phpunit
  slack:
    image: plugins/slack
    channel: '#general'
    username: 'Drone 传说中的持续集成'
    webhook: 'https://hooks.slack.com/services/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'
    when:
      status: [ started, success, failure ]