---
# locale: en_US
# session_driver: null
# session_path: /tmp/session
# session_name: gini-session
session_cookie:
  lifetime: 0
  path: /
  domain: ~
timezone: Asia/Shanghai
postmaster:
  address: support@geneegroup.com
  name: Genee
log:
  ident: gini
  option: 5
  facility: 8
rurl_mod:
    js:
        query: '_v=$(VERSION)&_t=$(TIMESTAMP)'
    css:
        query: '_v=$(VERSION)'
...
